### ISSUE TITLE
Ticker strings in cleanUp are not completely formatted

### ISSUE THREAD

**Issue by EugeneCPRO** [EugeneCPRO/toolBeta-main#1]
![image](https://github.com/EugeneCPRO/toolBeta-main/assets/95511781/4eef7449-f023-40ad-af28-aff81bd5c439)

[ appears on first entry, ] appears on last

needs resolved

**Comment by EugeneCPRO** [comment]
[image](https://github.com/EugeneCPRO/toolBeta-main/assets/95511781/ed913f33-d1d9-47c5-b2e6-85235b53e311)

**Comment by genedlorean** [comment]
This is resolve through the use of keys (which I didn't know about lmao, was filtering through everything as a string)

![image](https://github.com/EugeneCPRO/toolBeta-main/assets/95511781/cd4e615b-2211-4fbd-bc70-e16004585616)
